### ISSUE TITLE
Request: Level should inherit from LevelUp

### ISSUE THREAD

**Issue by deian** [Level/packager#11]
The module returns a `LevelUp` object, but deceivingly `Level` does not inherit from `LevelUp`. Any chance of exposing a constructor that is an instance of `LevelUp`?

**Comment by juliangruber** [comment]
while in general I agree, it's still useful to know your use case. why do you want or need this change?

**Comment by deian** [comment]
Thanks @juliangruber. I am working on a virtualization layer where I'm exposing a wrapped Level object.
