### ISSUE TITLE
Depend on levelup with ^

### ISSUE THREAD

**Issue by mcollina** [Level/packager#20]
Folks, I think that we should depend on LevelUp with ^.
Or remember to ship level-packager when we ship levelup.

**Comment by ralphtheninja** [comment]
I'm +-0 on it. I realize depending on `^` is practical but since `level-packager` *is* `levelup` + `repair()` and `destroy()` (api wise) its version will basically not say anything. Basically this would mean `level-packager` will only change major version when `levelup` changes major.

**Comment by ralphtheninja** [comment]
@mcollina I'll get this fixed for `level-packager@2.0.0`
