### ISSUE TITLE
level-packager should test level-packager.js and not use leveldown

### ISSUE THREAD

**Issue by ralphtheninja** [Level/packager#62]
I propose something like:

- [x] move current `test.js` to e.g. `abstract/test.js` (a la `abstract-leveldown` style), also break them apart into e.g. `.all()` etc (https://github.com/Level/packager/issues/61)
- [x] create new `test.js` file that tests the `level-packager.js` constructor
- [x] code in `if (!module.parent) {}` should be moved to `level` and `level-browserify`
- [x] remove `leveldown` devDependency
- [x] clean up compiler stuff from `.travis.yml`

**Comment by ralphtheninja** [comment]
When upgrading `level-packager` in dependent modules, they should use the `abstract/test.js` file and pick `.all()` (for `level` and `level-browserify`) or a sub set of `.all()` accordingly.

**Comment by vweevers** [comment]
Sounds good!
